[minio]
endpoint_url     = http://31.97.241.212:9002
access_key_id    = elinwinter
secret_access_key = elinwinter
allow_http       = true
bucket_name      = elinwinter-bucket

[api]
base_url         = https://earthquake.usgs.gov/fdsnws/event/1
events_endpoint  = query
catalogs_endpoint = catalogs
contributors_endpoint = contributors

[events_params]
lookback_hours   = 24
min_magnitude    = 2.5
orderby          = time
limit            = 20000
format           = geojson

[datalake]
bronze_layer     = bronze
api_name         = usgs_earthquake_api
events_dir       = events
catalogs_dir     = catalogs
contributors_dir = contributors

[delta]
vacuum_retention_hours = 168
optimize_enabled = true